name: cifra_app
description: "Accounting app designed to be among the best"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.0
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.7
  go_router: ^14.6.2
  sqflite_common_ffi: ^2.3.4+4
  path_provider: ^2.1.5
  path: ^1.9.0
  cv: ^1.1.3
  shared_preferences: ^2.5.2
  flutter_shaders: ^0.1.3
  sqflite: ^2.4.1
  google_fonts: ^6.2.1
  marquee: ^2.3.0
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^3.0.6
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/
    - fonts/

  shaders:
    - assets/shaders/pixel_shader.frag

  fonts:
    - family: C1fra_Icons
      fonts:
        - asset: fonts/C1fra-Icons.ttf
