// Mocks generated by Mockito 5.4.6 from annotations
// in cifra_app/test/features/wallet/domain/bloc/history_bloc/bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:cifra_app/common/models/get_filter.dart' as _i5;
import 'package:cifra_app/common/models/money.dart' as _i7;
import 'package:cifra_app/repositories/categories/models/category.dart' as _i6;
import 'package:cifra_app/repositories/transactions/models/transaction.dart'
    as _i4;
import 'package:cifra_app/repositories/transactions/repository.dart' as _i8;
import 'package:cv/cv.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:sqflite/sqflite.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCvField_0<T extends Object?> extends _i1.SmartFake
    implements _i2.CvField<T> {
  _FakeCvField_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCvModelField_1<T extends _i2.CvModel> extends _i1.SmartFake
    implements _i2.CvModelField<T> {
  _FakeCvModelField_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabase_2 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransaction_3 extends _i1.SmartFake implements _i4.Transaction {
  _FakeTransaction_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetFilter_4 extends _i1.SmartFake implements _i5.GetFilter {
  _FakeGetFilter_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Transaction].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransaction extends _i1.Mock implements _i4.Transaction {
  @override
  _i2.CvField<String> get title => (super.noSuchMethod(
        Invocation.getter(#title),
        returnValue: _FakeCvField_0<String>(
          this,
          Invocation.getter(#title),
        ),
        returnValueForMissingStub: _FakeCvField_0<String>(
          this,
          Invocation.getter(#title),
        ),
      ) as _i2.CvField<String>);

  @override
  _i2.CvField<_i4.TransactionType> get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _FakeCvField_0<_i4.TransactionType>(
          this,
          Invocation.getter(#type),
        ),
        returnValueForMissingStub: _FakeCvField_0<_i4.TransactionType>(
          this,
          Invocation.getter(#type),
        ),
      ) as _i2.CvField<_i4.TransactionType>);

  @override
  _i2.CvModelField<_i6.Category> get category => (super.noSuchMethod(
        Invocation.getter(#category),
        returnValue: _FakeCvModelField_1<_i6.Category>(
          this,
          Invocation.getter(#category),
        ),
        returnValueForMissingStub: _FakeCvModelField_1<_i6.Category>(
          this,
          Invocation.getter(#category),
        ),
      ) as _i2.CvModelField<_i6.Category>);

  @override
  _i2.CvField<_i7.Money> get value => (super.noSuchMethod(
        Invocation.getter(#value),
        returnValue: _FakeCvField_0<_i7.Money>(
          this,
          Invocation.getter(#value),
        ),
        returnValueForMissingStub: _FakeCvField_0<_i7.Money>(
          this,
          Invocation.getter(#value),
        ),
      ) as _i2.CvField<_i7.Money>);

  @override
  _i2.CvField<DateTime> get date => (super.noSuchMethod(
        Invocation.getter(#date),
        returnValue: _FakeCvField_0<DateTime>(
          this,
          Invocation.getter(#date),
        ),
        returnValueForMissingStub: _FakeCvField_0<DateTime>(
          this,
          Invocation.getter(#date),
        ),
      ) as _i2.CvField<DateTime>);

  @override
  _i2.CvField<String?> get description => (super.noSuchMethod(
        Invocation.getter(#description),
        returnValue: _FakeCvField_0<String?>(
          this,
          Invocation.getter(#description),
        ),
        returnValueForMissingStub: _FakeCvField_0<String?>(
          this,
          Invocation.getter(#description),
        ),
      ) as _i2.CvField<String?>);

  @override
  List<_i2.CvField<Object?>> get fields => (super.noSuchMethod(
        Invocation.getter(#fields),
        returnValue: <_i2.CvField<Object?>>[],
        returnValueForMissingStub: <_i2.CvField<Object?>>[],
      ) as List<_i2.CvField<Object?>>);

  @override
  _i2.CvField<int> get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _FakeCvField_0<int>(
          this,
          Invocation.getter(#id),
        ),
        returnValueForMissingStub: _FakeCvField_0<int>(
          this,
          Invocation.getter(#id),
        ),
      ) as _i2.CvField<int>);

  @override
  void fromMap(
    Map<dynamic, dynamic>? map, {
    List<String>? columns,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #fromMap,
          [map],
          {#columns: columns},
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, Object?> toMap({
    List<String>? columns,
    bool? includeMissingValue = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [],
          {
            #columns: columns,
            #includeMissingValue: includeMissingValue,
          },
        ),
        returnValue: <String, Object?>{},
        returnValueForMissingStub: <String, Object?>{},
      ) as Map<String, Object?>);

  @override
  _i2.CvField<T>? field<T extends Object?>(String? name) => (super.noSuchMethod(
        Invocation.method(
          #field,
          [name],
        ),
        returnValueForMissingStub: null,
      ) as _i2.CvField<T>?);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i8.TransactionRepository {
  @override
  _i3.Database get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeDatabase_2(
          this,
          Invocation.getter(#db),
        ),
        returnValueForMissingStub: _FakeDatabase_2(
          this,
          Invocation.getter(#db),
        ),
      ) as _i3.Database);

  @override
  _i9.Stream<bool> get shouldUpdateTransactions => (super.noSuchMethod(
        Invocation.getter(#shouldUpdateTransactions),
        returnValue: _i9.Stream<bool>.empty(),
        returnValueForMissingStub: _i9.Stream<bool>.empty(),
      ) as _i9.Stream<bool>);

  @override
  _i9.Future<_i4.Transaction?> getById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i9.Future<_i4.Transaction?>.value(),
        returnValueForMissingStub: _i9.Future<_i4.Transaction?>.value(),
      ) as _i9.Future<_i4.Transaction?>);

  @override
  _i9.Future<List<_i4.Transaction>> getList({
    int? offset,
    int? limit,
    bool? desc = false,
    _i5.GetFilter? filter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getList,
          [],
          {
            #offset: offset,
            #limit: limit,
            #desc: desc,
            #filter: filter,
          },
        ),
        returnValue:
            _i9.Future<List<_i4.Transaction>>.value(<_i4.Transaction>[]),
        returnValueForMissingStub:
            _i9.Future<List<_i4.Transaction>>.value(<_i4.Transaction>[]),
      ) as _i9.Future<List<_i4.Transaction>>);

  @override
  _i9.Future<_i4.Transaction> save(_i4.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #save,
          [transaction],
        ),
        returnValue: _i9.Future<_i4.Transaction>.value(_FakeTransaction_3(
          this,
          Invocation.method(
            #save,
            [transaction],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i4.Transaction>.value(_FakeTransaction_3(
          this,
          Invocation.method(
            #save,
            [transaction],
          ),
        )),
      ) as _i9.Future<_i4.Transaction>);

  @override
  _i9.Future<List<_i4.Transaction>> saveAll(
          List<_i4.Transaction>? transacions) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAll,
          [transacions],
        ),
        returnValue:
            _i9.Future<List<_i4.Transaction>>.value(<_i4.Transaction>[]),
        returnValueForMissingStub:
            _i9.Future<List<_i4.Transaction>>.value(<_i4.Transaction>[]),
      ) as _i9.Future<List<_i4.Transaction>>);

  @override
  _i9.Future<int> delete(_i4.Transaction? transaction) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [transaction],
        ),
        returnValue: _i9.Future<int>.value(0),
        returnValueForMissingStub: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<dynamic> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i9.Future<dynamic>.value(),
        returnValueForMissingStub: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);
}

/// A class which mocks [GetFilter].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFilter extends _i1.Mock implements _i5.GetFilter {
  @override
  String get whereRaw => (super.noSuchMethod(
        Invocation.getter(#whereRaw),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#whereRaw),
        ),
        returnValueForMissingStub: _i10.dummyValue<String>(
          this,
          Invocation.getter(#whereRaw),
        ),
      ) as String);

  @override
  List<dynamic> get whereRawArgs => (super.noSuchMethod(
        Invocation.getter(#whereRawArgs),
        returnValue: <dynamic>[],
        returnValueForMissingStub: <dynamic>[],
      ) as List<dynamic>);

  @override
  String get where => (super.noSuchMethod(
        Invocation.getter(#where),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#where),
        ),
        returnValueForMissingStub: _i10.dummyValue<String>(
          this,
          Invocation.getter(#where),
        ),
      ) as String);

  @override
  List<dynamic> get whereArgs => (super.noSuchMethod(
        Invocation.getter(#whereArgs),
        returnValue: <dynamic>[],
        returnValueForMissingStub: <dynamic>[],
      ) as List<dynamic>);

  @override
  _i5.GetFilter operator &(_i5.GetFilter? other) => (super.noSuchMethod(
        Invocation.method(
          #&,
          [other],
        ),
        returnValue: _FakeGetFilter_4(
          this,
          Invocation.method(
            #&,
            [other],
          ),
        ),
        returnValueForMissingStub: _FakeGetFilter_4(
          this,
          Invocation.method(
            #&,
            [other],
          ),
        ),
      ) as _i5.GetFilter);
}
