// Mocks generated by Mockito 5.4.6 from annotations
// in cifra_app/test/features/create_transaction/domain/create_transaction/bloc.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:cifra_app/common/models/get_filter.dart' as _i11;
import 'package:cifra_app/common/models/money.dart' as _i13;
import 'package:cifra_app/repositories/categories/models/category.dart' as _i6;
import 'package:cifra_app/repositories/categories/repository.dart' as _i14;
import 'package:cifra_app/repositories/currency_exchange/exchange_rate_repository.dart'
    as _i12;
import 'package:cifra_app/repositories/currency_exchange/models/exchage_rate.dart'
    as _i5;
import 'package:cifra_app/repositories/transactions/models/transaction.dart'
    as _i4;
import 'package:cifra_app/repositories/transactions/repository.dart' as _i10;
import 'package:cifra_app/repositories/user/models/user.dart' as _i2;
import 'package:cifra_app/repositories/user/repository.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i9;
import 'package:sqflite/sqflite.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabase_1 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransaction_2 extends _i1.SmartFake implements _i4.Transaction {
  _FakeTransaction_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExchangeRate_3 extends _i1.SmartFake implements _i5.ExchangeRate {
  _FakeExchangeRate_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCategory_4 extends _i1.SmartFake implements _i6.Category {
  _FakeCategory_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i7.UserRepository {
  @override
  _i8.Future<dynamic> init({_i9.SharedPreferencesWithCache? prefs}) =>
      (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
          {#prefs: prefs},
        ),
        returnValue: _i8.Future<dynamic>.value(),
        returnValueForMissingStub: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);

  @override
  _i8.Future<dynamic> save(_i2.User? user) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [user],
        ),
        returnValue: _i8.Future<dynamic>.value(),
        returnValueForMissingStub: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);

  @override
  _i2.User get() => (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
        ),
        returnValue: _FakeUser_0(
          this,
          Invocation.method(
            #get,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeUser_0(
          this,
          Invocation.method(
            #get,
            [],
          ),
        ),
      ) as _i2.User);

  @override
  _i8.Future<dynamic> reset() => (super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValue: _i8.Future<dynamic>.value(),
        returnValueForMissingStub: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i10.TransactionRepository {
  @override
  _i3.Database get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeDatabase_1(
          this,
          Invocation.getter(#db),
        ),
        returnValueForMissingStub: _FakeDatabase_1(
          this,
          Invocation.getter(#db),
        ),
      ) as _i3.Database);

  @override
  _i8.Stream<bool> get shouldUpdateTransactions => (super.noSuchMethod(
        Invocation.getter(#shouldUpdateTransactions),
        returnValue: _i8.Stream<bool>.empty(),
        returnValueForMissingStub: _i8.Stream<bool>.empty(),
      ) as _i8.Stream<bool>);

  @override
  _i8.Future<_i4.Transaction?> getById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i8.Future<_i4.Transaction?>.value(),
        returnValueForMissingStub: _i8.Future<_i4.Transaction?>.value(),
      ) as _i8.Future<_i4.Transaction?>);

  @override
  _i8.Future<List<_i4.Transaction>> getList({
    int? offset,
    int? limit,
    bool? desc = false,
    _i11.GetFilter? filter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getList,
          [],
          {
            #offset: offset,
            #limit: limit,
            #desc: desc,
            #filter: filter,
          },
        ),
        returnValue:
            _i8.Future<List<_i4.Transaction>>.value(<_i4.Transaction>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i4.Transaction>>.value(<_i4.Transaction>[]),
      ) as _i8.Future<List<_i4.Transaction>>);

  @override
  _i8.Future<_i4.Transaction> save(_i4.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #save,
          [transaction],
        ),
        returnValue: _i8.Future<_i4.Transaction>.value(_FakeTransaction_2(
          this,
          Invocation.method(
            #save,
            [transaction],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i4.Transaction>.value(_FakeTransaction_2(
          this,
          Invocation.method(
            #save,
            [transaction],
          ),
        )),
      ) as _i8.Future<_i4.Transaction>);

  @override
  _i8.Future<List<_i4.Transaction>> saveAll(
          List<_i4.Transaction>? transacions) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAll,
          [transacions],
        ),
        returnValue:
            _i8.Future<List<_i4.Transaction>>.value(<_i4.Transaction>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i4.Transaction>>.value(<_i4.Transaction>[]),
      ) as _i8.Future<List<_i4.Transaction>>);

  @override
  _i8.Future<int> delete(_i4.Transaction? transaction) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [transaction],
        ),
        returnValue: _i8.Future<int>.value(0),
        returnValueForMissingStub: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<dynamic> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i8.Future<dynamic>.value(),
        returnValueForMissingStub: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);
}

/// A class which mocks [ExchangeRateRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExchangeRateRepository extends _i1.Mock
    implements _i12.ExchangeRateRepository {
  @override
  _i8.Future<_i5.ExchangeRate> getRate({
    String? date = 'latest',
    required _i13.Currency? currency,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRate,
          [],
          {
            #date: date,
            #currency: currency,
          },
        ),
        returnValue: _i8.Future<_i5.ExchangeRate>.value(_FakeExchangeRate_3(
          this,
          Invocation.method(
            #getRate,
            [],
            {
              #date: date,
              #currency: currency,
            },
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.ExchangeRate>.value(_FakeExchangeRate_3(
          this,
          Invocation.method(
            #getRate,
            [],
            {
              #date: date,
              #currency: currency,
            },
          ),
        )),
      ) as _i8.Future<_i5.ExchangeRate>);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i14.CategoryRepository {
  @override
  _i3.Database get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeDatabase_1(
          this,
          Invocation.getter(#db),
        ),
        returnValueForMissingStub: _FakeDatabase_1(
          this,
          Invocation.getter(#db),
        ),
      ) as _i3.Database);

  @override
  _i8.Stream<bool> get shouldUpdateCategories => (super.noSuchMethod(
        Invocation.getter(#shouldUpdateCategories),
        returnValue: _i8.Stream<bool>.empty(),
        returnValueForMissingStub: _i8.Stream<bool>.empty(),
      ) as _i8.Stream<bool>);

  @override
  _i8.Future<_i6.Category?> getById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i8.Future<_i6.Category?>.value(),
        returnValueForMissingStub: _i8.Future<_i6.Category?>.value(),
      ) as _i8.Future<_i6.Category?>);

  @override
  _i8.FutureOr<List<_i6.Category>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i8.Future<List<_i6.Category>>.value(<_i6.Category>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i6.Category>>.value(<_i6.Category>[]),
      ) as _i8.FutureOr<List<_i6.Category>>);

  @override
  _i8.FutureOr<List<_i6.Category>> getList({
    int? offset,
    int? limit,
    bool? desc = false,
    _i11.GetFilter? filter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getList,
          [],
          {
            #offset: offset,
            #limit: limit,
            #desc: desc,
            #filter: filter,
          },
        ),
        returnValue: _i8.Future<List<_i6.Category>>.value(<_i6.Category>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i6.Category>>.value(<_i6.Category>[]),
      ) as _i8.FutureOr<List<_i6.Category>>);

  @override
  _i8.Future<_i6.Category> save(_i6.Category? value) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [value],
        ),
        returnValue: _i8.Future<_i6.Category>.value(_FakeCategory_4(
          this,
          Invocation.method(
            #save,
            [value],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i6.Category>.value(_FakeCategory_4(
          this,
          Invocation.method(
            #save,
            [value],
          ),
        )),
      ) as _i8.Future<_i6.Category>);

  @override
  _i8.Future<List<_i6.Category>> saveAll(List<_i6.Category>? values) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAll,
          [values],
        ),
        returnValue: _i8.Future<List<_i6.Category>>.value(<_i6.Category>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i6.Category>>.value(<_i6.Category>[]),
      ) as _i8.Future<List<_i6.Category>>);

  @override
  _i8.Future<int> delete(_i6.Category? value) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [value],
        ),
        returnValue: _i8.Future<int>.value(0),
        returnValueForMissingStub: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<dynamic> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i8.Future<dynamic>.value(),
        returnValueForMissingStub: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);
}
