// Mocks generated by Mockito 5.4.5 from annotations
// in cifra_app/test/features/onboarding/domain/intro_bloc/bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cifra_app/repositories/user/models/user.dart' as _i2;
import 'package:cifra_app/repositories/user/repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i3.UserRepository {
  @override
  _i4.Future<dynamic> init({_i5.SharedPreferencesWithCache? prefs}) =>
      (super.noSuchMethod(
        Invocation.method(#init, [], {#prefs: prefs}),
        returnValue: _i4.Future<dynamic>.value(),
        returnValueForMissingStub: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> save(_i2.User? user) => (super.noSuchMethod(
        Invocation.method(#save, [user]),
        returnValue: _i4.Future<dynamic>.value(),
        returnValueForMissingStub: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i2.User get() => (super.noSuchMethod(
        Invocation.method(#get, []),
        returnValue: _FakeUser_0(this, Invocation.method(#get, [])),
        returnValueForMissingStub: _FakeUser_0(
          this,
          Invocation.method(#get, []),
        ),
      ) as _i2.User);

  @override
  _i4.Future<dynamic> reset() => (super.noSuchMethod(
        Invocation.method(#reset, []),
        returnValue: _i4.Future<dynamic>.value(),
        returnValueForMissingStub: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);
}
